/**
 * The carrier-agnostic path into the closing percentage.
 *
 * ── Why this exists ──────────────────────────────────────────────────────────
 *
 * The closing percentage prices every agency, and its numerator is submitted
 * applications. Until this file, the ONLY code that ever set `submittedAt` was
 * `markAutomationCompleted` in `services/carrier-rpa/application-store.ts`,
 * reached from one route, when the American Amicable RPA finished.
 *
 * The quote panel offers eleven carriers. Business written with the other ten
 * -- Aflac, SBLI, CICA, GTL, Corebridge, TransAmerica, AHL, Royal Neighbors,
 * Gerber, Mutual of Omaha -- was never counted. That is not a reporting gap: a
 * numerator that is missing ten carriers understates the closing percentage,
 * and a lower closing percentage is a HIGHER rate on the curve. Every agency
 * writing outside American Amicable was being overcharged for doing so.
 *
 * So this is a second path, beside the RPA rather than through it. The RPA is
 * untouched: `american-amicable.ts`, `routes/automation.ts` and the existing
 * behaviour of `application-store.ts` are all exactly as they were.
 *
 * ── The two paths are the same application ───────────────────────────────────
 *
 * `source` records which path wrote the row, and NOTHING in the measurement
 * branches on it. `services/rating/measurement.ts` counts an
 * `InsuranceCarrierApplication` with a non-null `submittedAt` and a null
 * `voidedAt`, whoever wrote it. An AGENT_ENTRY row spends a credit through the
 * same ledger, on the same Delivery Day, at the same rate. The column exists so
 * an agency reconciling against carrier statements can see which rows it typed
 * and which the automation typed -- not so anything can price them differently.
 *
 * ── What this path does not collect ──────────────────────────────────────────
 *
 * No SSN, no routing number, no account number. The agent has already written
 * the business on the carrier's own portal or paper; this records THAT IT
 * HAPPENED, and asking an agent to retype a social security number into a
 * second system to make a count come out right would be collecting regulated
 * data for a billing measurement. `ssnEncrypted`, `routingNumberEncrypted`,
 * `accountNumberEncrypted` and every last-4 field are left untouched.
 */

import { Prisma } from '@prisma/client';

import { getPrismaClient } from '../../lib/prisma.js';

/** The premium modes an agent can write business in. */
export type PaymentMode = 'MONTHLY' | 'QUARTERLY' | 'SEMI_ANNUAL' | 'ANNUAL';

/** Payments per year, by mode. The whole of the annualisation rule. */
const PAYMENTS_PER_YEAR: Record<PaymentMode, number> = {
  MONTHLY: 12,
  QUARTERLY: 4,
  SEMI_ANNUAL: 2,
  ANNUAL: 1,
};

export const PAYMENT_MODES = Object.keys(PAYMENTS_PER_YEAR) as PaymentMode[];

/**
 * The premium as written, annualised, to two decimals.
 *
 * Rounded here, once, and stored -- rather than derived per row at read time --
 * so that a sum over a day of mixed modes cannot disagree with the sum of the
 * rows a principal is reading on the screen.
 */
export function annualizePremium(modalPremium: number, paymentMode: PaymentMode): number {
  return Math.round(modalPremium * PAYMENTS_PER_YEAR[paymentMode] * 100) / 100;
}

/**
 * What an agent logged.
 *
 * `tenantId` and `createdById` come from the authenticated principal and are
 * never read off a request body: the tenant is the boundary between two
 * agencies' numerators, and `createdById` is what the per-agent breakdown on
 * the delivery page attributes production by.
 */
export interface AgentApplicationInput {
  tenantId: string;
  /** The agent who wrote the business. `getAgentBreakdown` attributes by this. */
  createdById: string;
  /** Generated by the agent's client per form instance. The idempotency key. */
  clientRequestId: string;

  callId?: string | null;
  insuranceLeadId?: string | null;

  carrier: string;
  product?: string | null;
  planType?: string | null;
  faceAmount: number;
  modalPremium: number;
  paymentMode: PaymentMode;
  carrierApplicationNumber?: string | null;

  firstName: string;
  lastName: string;
  dob?: string | null;
  state?: string | null;
  phone?: string | null;
}

/**
 * Record an application an agent wrote, on any carrier, and spend its credit.
 *
 * Does what `markAutomationCompleted` does, minus the RPA: the row reaches
 * SUBMITTED with a `submittedAt`, and the credit is consumed afterwards,
 * outside the write, swallowing its own failures.
 *
 * Returns the application row. On a retry of a submit that already landed, it
 * returns the row that landed rather than writing a second one.
 */
export async function recordAgentApplication(
  input: AgentApplicationInput
): Promise<Record<string, unknown>> {
  const prisma = getPrismaClient();
  const submittedAt = new Date();

  const annualizedPremium = annualizePremium(input.modalPremium, input.paymentMode);

  let application: { id: string; tenantId: string; submittedAt: Date | null } & Record<
    string,
    unknown
  >;

  try {
    /*
     * One statement, deliberately.
     *
     * `markAutomationCompleted` explains at length why SUBMITTED and
     * `submittedAt` must be written together and fail together: a row left
     * SUBMITTED with a null `submittedAt` is an application the agency made
     * that the closing percentage never counts, and a silently uncounted
     * application is a silently wrong price. The same holds here, and a single
     * `create` gives it for free -- there is no second statement to fail.
     */
    application = (await prisma.insuranceCarrierApplication.create({
      data: {
        tenantId: input.tenantId,
        source: 'AGENT_ENTRY',
        status: 'SUBMITTED',
        submittedAt,
        createdById: input.createdById,
        clientRequestId: input.clientRequestId,

        callId: input.callId ?? null,
        insuranceLeadId: input.insuranceLeadId ?? null,

        carrier: input.carrier,
        /*
         * Empty rather than absent when the agent did not name a product.
         *
         * `product` carries the schema default 'Senior Choice', which is an
         * American Amicable product. Leaving it undefined would let that
         * default apply and put an American Amicable product name on an Aflac
         * application -- a wrong value on the screen an agency reconciles
         * against carrier statements. An empty string reads as "not recorded",
         * which is what it is.
         */
        product: input.product ?? '',
        planType: input.planType ?? null,
        faceAmount: input.faceAmount,
        modalPremium: new Prisma.Decimal(input.modalPremium.toFixed(2)),
        paymentMode: input.paymentMode,
        annualizedPremium: new Prisma.Decimal(annualizedPremium.toFixed(2)),
        /*
         * `monthlyPremium` is the RPA's column and this path does not own it,
         * but every existing reader of an application's premium reads it. So it
         * is written too, from the annualised figure, and an annual-mode
         * application shows a sensible monthly equivalent to a screen that has
         * never heard of `paymentMode` rather than showing the annual number as
         * if it were a monthly one.
         */
        monthlyPremium: new Prisma.Decimal((annualizedPremium / 12).toFixed(2)),
        carrierApplicationNumber: input.carrierApplicationNumber ?? null,

        firstName: input.firstName,
        lastName: input.lastName,
        dob: input.dob ?? null,
        state: input.state ?? null,
        phone: input.phone ?? null,

        // `automationStatus` keeps its PENDING default. It is unused on this
        // path -- there is no automation run to track -- and giving it a
        // meaning here would make it ambiguous on the path that does use it.
      },
    })) as typeof application;
  } catch (error) {
    /*
     * A retried submit is one application.
     *
     * The agent's client generates one `clientRequestId` when the form mounts
     * and reuses it on every retry, so a submit that timed out after the row
     * landed, a double-clicked button, and a Retry after a failed response all
     * arrive carrying the same key. The unique index on
     * (tenantId, clientRequestId) makes the second one a P2002, and the right
     * answer to it is the row that already exists -- not an error the agent
     * reads as "it did not save", and not a second application the agency is
     * charged a second credit for.
     *
     * Deliberately keyed on the FORM INSTANCE and not on the call: a couple
     * insuring together is two applications from one call, and a per-call key
     * would silently drop the second one.
     */
    if (error instanceof Prisma.PrismaClientKnownRequestError && error.code === 'P2002') {
      const existing = await prisma.insuranceCarrierApplication.findFirst({
        where: { tenantId: input.tenantId, clientRequestId: input.clientRequestId },
      });
      if (existing) return existing as unknown as Record<string, unknown>;
    }
    throw error;
  }

  /*
   * The application has reached submitted state, so it costs one credit.
   *
   * Deliberately after the write, deliberately not in a transaction, and
   * deliberately swallowed -- the three reasons `application-store.ts` gives at
   * length apply here unchanged. The business is written at the carrier by the
   * time an agent logs it; a ledger failure must not roll back or refuse a
   * submission that has already happened, and it is not lost money either,
   * because `reconcileDeliveryDay` in `credit-ledger.ts` writes a row that
   * evening for every application submitted on the Delivery Day that does not
   * have one yet.
   *
   * The imports are dynamic for the same reason they are there: the billing
   * modules pull in the whole ledger and settlement graph, and this service is
   * loaded on the agent's submit path.
   */
  try {
    const { isEnrolledForBilling } = await import('../billing/terms.js');

    /*
     * Only an agency explicitly enrolled in billing is metered. An unenrolled
     * agency's applications write no ledger row at all -- not a consumption,
     * not an overrun, nothing -- and still count in the measurement, which is
     * what the closing percentage is for.
     */
    if (!(await isEnrolledForBilling(prisma, input.tenantId))) return application;

    const { consumeCreditForApplication } = await import('../billing/credit-ledger.js');
    const { calendarDayOf } = await import('../rating/calendar-day.js');

    await consumeCreditForApplication({
      tenantId: input.tenantId,
      applicationId: application.id,
      // The Delivery Day the application is ATTRIBUTED to: the day it was
      // submitted, read back off the row rather than from `new Date()`.
      deliveryDay: calendarDayOf(application.submittedAt ?? submittedAt),
    });
  } catch (error) {
    console.error(
      `[billing] Could not record a credit for application ${application.id}; ` +
        'the settlement reconciliation pass will record it.',
      error
    );
  }

  return application as unknown as Record<string, unknown>;
}
