/**
 * What an agent must record for an application to count.
 *
 * ── Why this is a module and not a `const` in the route ──────────────────────
 *
 * It used to live inside `routes/applications.ts`, which was fine while
 * `POST /api/v1/applications` was the only way in. It is no longer: saving a
 * call with the disposition `APPLICATION_SUBMITTED` carries the same
 * application in the same request, and that endpoint has to accept EXACTLY the
 * same fields on EXACTLY the same terms.
 *
 * Two copies of this list would drift, and the direction they drift in is not
 * symmetric. The numerator of the closing percentage is submitted
 * applications, and a lower closing percentage is a HIGHER rate on the curve:
 * an endpoint that accepted a thinner application than the other would let
 * rows in that the agency cannot reconcile, or -- worse -- refuse rows that
 * should have counted and quietly raise what the agency pays. One schema, two
 * importers.
 *
 * ── Required is required ─────────────────────────────────────────────────────
 *
 * `carrier`, `faceAmount`, `modalPremium`, `firstName` and `lastName` are not
 * optional and have no defaults. An application is the record of business
 * written at a carrier; a row that cannot name the carrier, the person or the
 * premium is not something an agency can match against a carrier statement,
 * and it is a row the agency is charged a credit for.
 *
 * `paymentMode` is the one field that defaults, to MONTHLY, because that is
 * what the overwhelming majority of final-expense business is written on and
 * `annualizePremium` needs a mode to turn a modal premium into an annual one.
 *
 * ── Trimmed before it is measured ────────────────────────────────────────────
 *
 * `z.string().min(1)` accepts a single space. A name field holding " " passes
 * validation, writes a blank onto the row, and prints as an empty cell on the
 * screen an agency reconciles against carrier statements -- which reads as a
 * missing name rather than as one nobody typed. Trimming first makes the
 * check mean what it says, and the trimmed value is what gets stored.
 */

import { z } from 'zod';

/** A string that must hold something once the whitespace is gone. */
const required = (max?: number) => {
  const base = z
    .string()
    .transform(value => value.trim())
    .pipe(z.string().min(1));
  return max === undefined ? base : base.pipe(z.string().max(max));
};

/**
 * The application body, shared by the applications route and the disposition
 * route. `callId` is NOT here: each caller supplies it differently -- the
 * applications route reads it off the request, the disposition route supplies
 * the call it just resolved -- and letting a client name one on the disposition
 * path would let it attach a sale to some other call.
 */
export const ApplicationInputSchema = z.object({
  /*
   * Generated by the agent's client when the form MOUNTS and reused on every
   * retry, so a submit that timed out after the row landed and the Retry that
   * follows it are one application. Required rather than optional: an
   * idempotency key the client may omit is one the client will omit on exactly
   * the request that needed it.
   */
  clientRequestId: z.string().uuid(),
  insuranceLeadId: z.string().optional(),

  carrier: required(80),
  product: z.string().optional(),
  planType: z.enum(['LEVEL', 'GRADED', 'ROP', 'GUARANTEED_ISSUE']).optional(),
  faceAmount: z.number().int().min(1000).max(500000),
  modalPremium: z.number().positive().max(5000),
  paymentMode: z.enum(['MONTHLY', 'QUARTERLY', 'SEMI_ANNUAL', 'ANNUAL']).default('MONTHLY'),
  carrierApplicationNumber: z.string().optional(),

  firstName: required(),
  lastName: required(),
  dob: z
    .string()
    .regex(/^\d{2}\/\d{2}\/\d{4}$/, 'dob must be MM/DD/YYYY')
    .optional(),
  state: z.string().optional(),
  phone: z.string().optional(),
  notes: z.string().optional(),
});

export type ApplicationInput = z.infer<typeof ApplicationInputSchema>;

/**
 * The same body, plus the `callId` the applications route lets a client name.
 *
 * That route has always accepted one and verifies it against the agency and
 * the agent before storing it -- see `call-attribution.ts`. The disposition
 * route deliberately does not use this variant.
 */
export const CreateApplicationSchema = ApplicationInputSchema.extend({
  callId: z.string().optional(),
});

/**
 * One line naming what is missing, for a person rather than for a log.
 *
 * The agent reading this is between calls with the next one ringing. "carrier:
 * Required; firstName: Required" tells them which boxes to fill; a stack trace
 * or a bare 400 tells them to try again and hope.
 */
export function describeApplicationIssues(error: z.ZodError): string {
  return error.issues
    .map(issue => `${issue.path.join('.') || 'application'}: ${issue.message}`)
    .join('; ');
}
