/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/numbers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List phone numbers
         * @description Retrieve a paginated list of phone numbers for the tenant
         */
        get: operations["listNumbers"];
        put?: never;
        /**
         * Provision a phone number
         * @description Request provisioning of a new phone number
         */
        post: operations["provisionNumber"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/numbers/{numberId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get phone number
         * @description Retrieve details of a specific phone number
         */
        get: operations["getNumber"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update phone number
         * @description Update phone number configuration
         */
        patch: operations["updateNumber"];
        trace?: never;
    };
    "/api/v1/campaigns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List campaigns
         * @description Retrieve a paginated list of campaigns
         */
        get: operations["listCampaigns"];
        put?: never;
        /**
         * Create campaign
         * @description Create a new campaign
         */
        post: operations["createCampaign"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/campaigns/{campaignId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get campaign
         * @description Retrieve details of a specific campaign
         */
        get: operations["getCampaign"];
        put?: never;
        post?: never;
        /**
         * Delete campaign
         * @description Archive a campaign
         */
        delete: operations["deleteCampaign"];
        options?: never;
        head?: never;
        /**
         * Update campaign
         * @description Update campaign configuration
         */
        patch: operations["updateCampaign"];
        trace?: never;
    };
    "/api/v1/flows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List flows
         * @description Retrieve a paginated list of call flows
         */
        get: operations["listFlows"];
        put?: never;
        /**
         * Create flow
         * @description Create a new call flow
         */
        post: operations["createFlow"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/flows/{flowId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get flow
         * @description Retrieve details of a specific flow
         */
        get: operations["getFlow"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update flow
         * @description Update flow configuration
         */
        patch: operations["updateFlow"];
        trace?: never;
    };
    "/api/v1/calls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List calls
         * @description Retrieve a paginated list of calls with filtering options
         */
        get: operations["listCalls"];
        put?: never;
        /**
         * Initiate call
         * @description Initiate a new outbound call
         */
        post: operations["initiateCall"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/calls/{callId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get call
         * @description Retrieve details of a specific call
         */
        get: operations["getCall"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recordings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List recordings
         * @description Retrieve a paginated list of call recordings
         */
        get: operations["listRecordings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recordings/{recordingId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get recording
         * @description Retrieve details of a specific recording
         */
        get: operations["getRecording"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/webhooks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List webhooks
         * @description Retrieve a paginated list of webhook configurations
         */
        get: operations["listWebhooks"];
        put?: never;
        /**
         * Create webhook
         * @description Create a new webhook configuration
         */
        post: operations["createWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/webhooks/{webhookId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get webhook
         * @description Retrieve details of a specific webhook
         */
        get: operations["getWebhook"];
        put?: never;
        post?: never;
        /**
         * Delete webhook
         * @description Delete a webhook configuration
         */
        delete: operations["deleteWebhook"];
        options?: never;
        head?: never;
        /**
         * Update webhook
         * @description Update webhook configuration
         */
        patch: operations["updateWebhook"];
        trace?: never;
    };
    "/api/v1/reporting/calls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Call analytics
         * @description Get aggregated call analytics and metrics
         */
        get: operations["getCallAnalytics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reporting/campaigns/{campaignId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Campaign performance
         * @description Get performance metrics for a specific campaign
         */
        get: operations["getCampaignPerformance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/billing/invoices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List invoices
         * @description Retrieve a paginated list of invoices
         */
        get: operations["listInvoices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/billing/invoices/{invoiceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get invoice
         * @description Retrieve details of a specific invoice
         */
        get: operations["getInvoice"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/billing/balance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get account balance
         * @description Retrieve current account balance information
         */
        get: operations["getAccountBalance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/v1/tenants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List tenants
         * @description Retrieve a paginated list of tenants (admin only)
         */
        get: operations["adminListTenants"];
        put?: never;
        /**
         * Create tenant
         * @description Provision a new tenant (admin only)
         */
        post: operations["adminCreateTenant"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/v1/tenants/{tenantId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get tenant
         * @description Retrieve details of a specific tenant (admin only)
         */
        get: operations["adminGetTenant"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update tenant
         * @description Update tenant configuration (admin only)
         */
        patch: operations["adminUpdateTenant"];
        trace?: never;
    };
    "/admin/api/v1/numbers/provision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Provision number
         * @description Provision a phone number for a tenant (admin only)
         */
        post: operations["adminProvisionNumber"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/v1/carriers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List carriers
         * @description Retrieve a paginated list of carriers (admin only)
         */
        get: operations["adminListCarriers"];
        put?: never;
        /**
         * Create carrier
         * @description Create a new carrier (admin only)
         */
        post: operations["adminCreateCarrier"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/v1/carriers/{carrierId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get carrier
         * @description Retrieve details of a specific carrier (admin only)
         */
        get: operations["adminGetCarrier"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update carrier
         * @description Update carrier configuration (admin only)
         */
        patch: operations["adminUpdateCarrier"];
        trace?: never;
    };
    "/admin/api/v1/trunks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List trunks
         * @description Retrieve a paginated list of trunks (admin only)
         */
        get: operations["adminListTrunks"];
        put?: never;
        /**
         * Create trunk
         * @description Create a new trunk (admin only)
         */
        post: operations["adminCreateTrunk"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/v1/trunks/{trunkId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get trunk
         * @description Retrieve details of a specific trunk (admin only)
         */
        get: operations["adminGetTrunk"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update trunk
         * @description Update trunk configuration (admin only)
         */
        patch: operations["adminUpdateTrunk"];
        trace?: never;
    };
    "/admin/api/v1/rate-cards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List rate cards
         * @description Retrieve a paginated list of rate cards (admin only)
         */
        get: operations["adminListRateCards"];
        put?: never;
        /**
         * Create rate card
         * @description Create a new rate card (admin only)
         */
        post: operations["adminCreateRateCard"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/v1/rate-cards/{rateCardId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get rate card
         * @description Retrieve details of a specific rate card (admin only)
         */
        get: operations["adminGetRateCard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update rate card
         * @description Update rate card configuration (admin only)
         */
        patch: operations["adminUpdateRateCard"];
        trace?: never;
    };
}

export type webhooks = Record<string, never>;

export interface components {
    schemas: {
        PaginationMeta: {
            /** @description Current page number */
            page: number;
            /** @description Items per page */
            limit: number;
            /** @description Total number of items */
            total: number;
            /** @description Total number of pages */
            totalPages: number;
        };
        Error: {
            error: {
                /** @description Error code */
                code: string;
                /** @description Human-readable error message */
                message: string;
                /** @description Additional error details */
                details?: Record<string, never>;
                /** @description Request ID for debugging */
                requestId?: string;
            };
        };
        PhoneNumber: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tenantId: string;
            /**
             * @description E.164 format phone number
             * @example +15551234567
             */
            number: string;
            /** Format: uuid */
            carrierId?: string | null;
            /** Format: uuid */
            trunkId?: string | null;
            status: components["schemas"]["PhoneNumberStatus"];
            /** @description Phone number capabilities (SMS, MMS, Voice, etc.) */
            capabilities?: Record<string, never>;
            metadata?: Record<string, never>;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        /** @enum {string} */
        PhoneNumberStatus: "ACTIVE" | "INACTIVE" | "PORTING" | "SUSPENDED";
        ProvisionNumberRequest: {
            /**
             * @description E.164 format phone number
             * @example +15551234567
             */
            number: string;
            /** @description Required capabilities */
            capabilities?: ("SMS" | "MMS" | "Voice")[];
            metadata?: Record<string, never>;
        };
        UpdateNumberRequest: {
            status?: components["schemas"]["PhoneNumberStatus"];
            metadata?: Record<string, never>;
        };
        NumberListResponse: {
            data?: components["schemas"]["PhoneNumber"][];
            meta?: components["schemas"]["PaginationMeta"];
        };
        Campaign: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tenantId: string;
            /** Format: uuid */
            publisherId: string;
            name: string;
            status: components["schemas"]["CampaignStatus"];
            /** Format: uuid */
            callerIdPoolId?: string | null;
            /** Format: uuid */
            flowId?: string | null;
            metadata?: Record<string, never>;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        /** @enum {string} */
        CampaignStatus: "ACTIVE" | "PAUSED" | "ARCHIVED";
        CreateCampaignRequest: {
            /** Format: uuid */
            publisherId: string;
            name: string;
            /** Format: uuid */
            callerIdPoolId?: string;
            /** Format: uuid */
            flowId?: string;
            metadata?: Record<string, never>;
        };
        UpdateCampaignRequest: {
            name?: string;
            status?: components["schemas"]["CampaignStatus"];
            /** Format: uuid */
            callerIdPoolId?: string;
            /** Format: uuid */
            flowId?: string;
            metadata?: Record<string, never>;
        };
        CampaignListResponse: {
            data?: components["schemas"]["Campaign"][];
            meta?: components["schemas"]["PaginationMeta"];
        };
        Flow: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tenantId: string;
            name: string;
            description?: string | null;
            status: components["schemas"]["FlowStatus"];
            metadata?: Record<string, never>;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        /** @enum {string} */
        FlowStatus: "DRAFT" | "ACTIVE" | "ARCHIVED";
        CreateFlowRequest: {
            name: string;
            description?: string;
            metadata?: Record<string, never>;
        };
        UpdateFlowRequest: {
            name?: string;
            description?: string;
            status?: components["schemas"]["FlowStatus"];
            metadata?: Record<string, never>;
        };
        FlowListResponse: {
            data?: components["schemas"]["Flow"][];
            meta?: components["schemas"]["PaginationMeta"];
        };
        Call: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tenantId: string;
            /** Format: uuid */
            campaignId?: string | null;
            /** Format: uuid */
            fromNumberId?: string | null;
            /** @description E.164 format */
            toNumber: string;
            /** @description External call identifier */
            callSid: string;
            status: components["schemas"]["CallStatus"];
            direction: components["schemas"]["CallDirection"];
            /** @description Duration in seconds */
            duration?: number | null;
            cost?: number | null;
            metadata?: Record<string, never>;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            startedAt?: string | null;
            /** Format: date-time */
            answeredAt?: string | null;
            /** Format: date-time */
            endedAt?: string | null;
        };
        /** @enum {string} */
        CallStatus: "INITIATED" | "RINGING" | "ANSWERED" | "COMPLETED" | "FAILED" | "BUSY" | "NO_ANSWER" | "CANCELLED";
        /** @enum {string} */
        CallDirection: "INBOUND" | "OUTBOUND";
        InitiateCallRequest: {
            /** Format: uuid */
            campaignId?: string;
            /** Format: uuid */
            fromNumberId?: string;
            /** @description E.164 format */
            toNumber: string;
            metadata?: Record<string, never>;
        };
        CallListResponse: {
            data?: components["schemas"]["Call"][];
            meta?: components["schemas"]["PaginationMeta"];
        };
        Recording: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            callId: string;
            /** Format: uuid */
            legId?: string | null;
            /** Format: uri */
            url: string;
            storageKey?: string | null;
            /** @description Duration in seconds */
            duration?: number | null;
            /** @default wav */
            format: string;
            /**
             * Format: int64
             * @description Size in bytes
             */
            size?: number | null;
            status: components["schemas"]["RecordingStatus"];
            metadata?: Record<string, never>;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        /** @enum {string} */
        RecordingStatus: "PROCESSING" | "COMPLETED" | "FAILED";
        RecordingListResponse: {
            data?: components["schemas"]["Recording"][];
            meta?: components["schemas"]["PaginationMeta"];
        };
        Webhook: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tenantId: string;
            /** Format: uri */
            url: string;
            events: ("call.started" | "call.answered" | "call.completed" | "recording.ready" | "invoice.finalized")[];
            status: components["schemas"]["WebhookStatus"];
            /** Format: date-time */
            lastTriggeredAt?: string | null;
            metadata?: Record<string, never>;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        /** @enum {string} */
        WebhookStatus: "ACTIVE" | "INACTIVE" | "FAILED";
        CreateWebhookRequest: {
            /** Format: uri */
            url: string;
            events: ("call.started" | "call.answered" | "call.completed" | "recording.ready" | "invoice.finalized")[];
            metadata?: Record<string, never>;
        };
        UpdateWebhookRequest: {
            /** Format: uri */
            url?: string;
            events?: ("call.started" | "call.answered" | "call.completed" | "recording.ready" | "invoice.finalized")[];
            status?: components["schemas"]["WebhookStatus"];
            metadata?: Record<string, never>;
        };
        WebhookListResponse: {
            data?: components["schemas"]["Webhook"][];
            meta?: components["schemas"]["PaginationMeta"];
        };
        CallAnalyticsResponse: {
            period: {
                /** Format: date-time */
                start?: string;
                /** Format: date-time */
                end?: string;
            };
            metrics: {
                totalCalls: number;
                answeredCalls?: number;
                completedCalls?: number;
                failedCalls?: number;
                /** @description Total duration in seconds */
                totalDuration?: number;
                /** @description Average duration in seconds */
                averageDuration?: number;
                totalCost?: string;
            };
            breakdown?: {
                dimension?: string;
                value?: string;
                metrics?: Record<string, never>;
            }[];
        };
        CampaignPerformanceResponse: {
            /** Format: uuid */
            campaignId: string;
            period: {
                /** Format: date-time */
                start?: string;
                /** Format: date-time */
                end?: string;
            };
            metrics: {
                totalCalls: number;
                answeredCalls?: number;
                /** @description Answer rate as percentage */
                answerRate?: number;
                completedCalls?: number;
                /** @description Completion rate as percentage */
                completionRate?: number;
                totalDuration?: number;
                averageDuration?: number;
                totalCost?: string;
            };
        };
        Invoice: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            billingAccountId: string;
            invoiceNumber: string;
            status: components["schemas"]["InvoiceStatus"];
            /** Format: date-time */
            periodStart: string;
            /** Format: date-time */
            periodEnd: string;
            subtotal: string;
            tax: string;
            total: string;
            /** Format: date-time */
            dueDate: string;
            /** Format: date-time */
            paidAt?: string | null;
            metadata?: Record<string, never>;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        /** @enum {string} */
        InvoiceStatus: "DRAFT" | "SENT" | "PAID" | "OVERDUE" | "CANCELLED";
        InvoiceListResponse: {
            data?: components["schemas"]["Invoice"][];
            meta?: components["schemas"]["PaginationMeta"];
        };
        BalanceResponse: {
            /** Format: uuid */
            billingAccountId: string;
            /** @default USD */
            currency: string;
            available: string;
            pending: string;
            held: string;
            total: string;
        };
        Tenant: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
            domain?: string | null;
            status: components["schemas"]["TenantStatus"];
            metadata?: Record<string, never>;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        /** @enum {string} */
        TenantStatus: "ACTIVE" | "SUSPENDED" | "INACTIVE";
        AdminCreateTenantRequest: {
            name: string;
            slug: string;
            domain?: string;
            metadata?: Record<string, never>;
        };
        AdminUpdateTenantRequest: {
            name?: string;
            slug?: string;
            domain?: string;
            status?: components["schemas"]["TenantStatus"];
            metadata?: Record<string, never>;
        };
        TenantListResponse: {
            data?: components["schemas"]["Tenant"][];
            meta?: components["schemas"]["PaginationMeta"];
        };
        Carrier: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tenantId: string;
            name: string;
            code: string;
            status: components["schemas"]["CarrierStatus"];
            metadata?: Record<string, never>;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        /** @enum {string} */
        CarrierStatus: "ACTIVE" | "INACTIVE";
        AdminCreateCarrierRequest: {
            /** Format: uuid */
            tenantId: string;
            name: string;
            code: string;
            metadata?: Record<string, never>;
        };
        AdminUpdateCarrierRequest: {
            name?: string;
            code?: string;
            status?: components["schemas"]["CarrierStatus"];
            metadata?: Record<string, never>;
        };
        CarrierListResponse: {
            data?: components["schemas"]["Carrier"][];
            meta?: components["schemas"]["PaginationMeta"];
        };
        Trunk: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tenantId: string;
            /** Format: uuid */
            carrierId: string;
            name: string;
            type: components["schemas"]["TrunkType"];
            host: string;
            port: number;
            username?: string | null;
            status: components["schemas"]["TrunkStatus"];
            metadata?: Record<string, never>;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        /** @enum {string} */
        TrunkType: "SIP" | "IAX2" | "WEBRTC";
        /** @enum {string} */
        TrunkStatus: "ACTIVE" | "INACTIVE" | "MAINTENANCE";
        AdminCreateTrunkRequest: {
            /** Format: uuid */
            tenantId: string;
            /** Format: uuid */
            carrierId: string;
            name: string;
            type: components["schemas"]["TrunkType"];
            host: string;
            port: number;
            username?: string;
            password?: string;
            metadata?: Record<string, never>;
        };
        AdminUpdateTrunkRequest: {
            name?: string;
            type?: components["schemas"]["TrunkType"];
            host?: string;
            port?: number;
            username?: string;
            password?: string;
            status?: components["schemas"]["TrunkStatus"];
            metadata?: Record<string, never>;
        };
        TrunkListResponse: {
            data?: components["schemas"]["Trunk"][];
            meta?: components["schemas"]["PaginationMeta"];
        };
        RateCard: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            billingAccountId: string;
            name: string;
            /** Format: date-time */
            effectiveFrom: string;
            /** Format: date-time */
            effectiveTo?: string | null;
            status: components["schemas"]["RateCardStatus"];
            /** @description Rate structure (JSON object) */
            rates: Record<string, never>;
            metadata?: Record<string, never>;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        /** @enum {string} */
        RateCardStatus: "ACTIVE" | "INACTIVE";
        AdminCreateRateCardRequest: {
            /** Format: uuid */
            billingAccountId: string;
            name: string;
            /** Format: date-time */
            effectiveFrom: string;
            /** Format: date-time */
            effectiveTo?: string;
            /** @description Rate structure (JSON object) */
            rates: Record<string, never>;
            metadata?: Record<string, never>;
        };
        AdminUpdateRateCardRequest: {
            name?: string;
            /** Format: date-time */
            effectiveFrom?: string;
            /** Format: date-time */
            effectiveTo?: string;
            status?: components["schemas"]["RateCardStatus"];
            rates?: Record<string, never>;
            metadata?: Record<string, never>;
        };
        RateCardListResponse: {
            data?: components["schemas"]["RateCard"][];
            meta?: components["schemas"]["PaginationMeta"];
        };
        AdminProvisionNumberRequest: {
            /** Format: uuid */
            tenantId: string;
            /** @description E.164 format phone number */
            number: string;
            /** Format: uuid */
            carrierId?: string;
            /** Format: uuid */
            trunkId?: string;
            capabilities?: ("SMS" | "MMS" | "Voice")[];
            metadata?: Record<string, never>;
        };
    };
    responses: {
        /** @description Bad request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "BAD_REQUEST",
                 *         "message": "Invalid request parameters",
                 *         "requestId": "req_1234567890"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Unauthorized */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "UNAUTHORIZED",
                 *         "message": "Invalid or missing API key",
                 *         "requestId": "req_1234567890"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Forbidden */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "FORBIDDEN",
                 *         "message": "Insufficient permissions",
                 *         "requestId": "req_1234567890"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "NOT_FOUND",
                 *         "message": "Resource not found",
                 *         "requestId": "req_1234567890"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Conflict (e.g., duplicate resource or idempotency key already used) */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "CONFLICT",
                 *         "message": "Resource already exists",
                 *         "requestId": "req_1234567890"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Rate limit exceeded */
        RateLimitExceeded: {
            headers: {
                /** @description Request limit per window */
                "X-RateLimit-Limit"?: number;
                /** @description Remaining requests in current window */
                "X-RateLimit-Remaining"?: number;
                /** @description Unix timestamp when rate limit resets */
                "X-RateLimit-Reset"?: number;
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "RATE_LIMIT_EXCEEDED",
                 *         "message": "Rate limit exceeded. Please try again later.",
                 *         "requestId": "req_1234567890"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description Page number (1-indexed) */
        Page: number;
        /** @description Number of items per page */
        Limit: number;
        /** @description Filter by status */
        FilterStatus: string;
        /** @description Idempotency key for request (valid for 24 hours) */
        IdempotencyKey: string;
        /** @description Phone number ID */
        NumberId: string;
        /** @description Campaign ID */
        CampaignId: string;
        /** @description Flow ID */
        FlowId: string;
        /** @description Call ID */
        CallId: string;
        /** @description Recording ID */
        RecordingId: string;
        /** @description Webhook ID */
        WebhookId: string;
        /** @description Invoice ID */
        InvoiceId: string;
        /** @description Tenant ID */
        TenantId: string;
        /** @description Carrier ID */
        CarrierId: string;
        /** @description Trunk ID */
        TrunkId: string;
        /** @description Rate card ID */
        RateCardId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}

export type $defs = Record<string, never>;

export interface operations {
    listNumbers: {
        parameters: {
            query?: {
                /** @description Page number (1-indexed) */
                page?: components["parameters"]["Page"];
                /** @description Number of items per page */
                limit?: components["parameters"]["Limit"];
                /** @description Filter by status */
                status?: components["parameters"]["FilterStatus"];
                /** @description Search by phone number (partial match) */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NumberListResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["RateLimitExceeded"];
        };
    };
    provisionNumber: {
        parameters: {
            query?: never;
            header?: {
                /** @description Idempotency key for request (valid for 24 hours) */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProvisionNumberRequest"];
            };
        };
        responses: {
            /** @description Number provisioned successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhoneNumber"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["RateLimitExceeded"];
        };
    };
    getNumber: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Phone number ID */
                numberId: components["parameters"]["NumberId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhoneNumber"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimitExceeded"];
        };
    };
    updateNumber: {
        parameters: {
            query?: never;
            header?: {
                /** @description Idempotency key for request (valid for 24 hours) */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                /** @description Phone number ID */
                numberId: components["parameters"]["NumberId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateNumberRequest"];
            };
        };
        responses: {
            /** @description Number updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhoneNumber"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimitExceeded"];
        };
    };
    listCampaigns: {
        parameters: {
            query?: {
                /** @description Page number (1-indexed) */
                page?: components["parameters"]["Page"];
                /** @description Number of items per page */
                limit?: components["parameters"]["Limit"];
                /** @description Filter by status */
                status?: components["parameters"]["FilterStatus"];
                /** @description Filter by publisher ID */
                publisherId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignListResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["RateLimitExceeded"];
        };
    };
    createCampaign: {
        parameters: {
            query?: never;
            header?: {
                /** @description Idempotency key for request (valid for 24 hours) */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCampaignRequest"];
            };
        };
        responses: {
            /** @description Campaign created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Campaign"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["RateLimitExceeded"];
        };
    };
    getCampaign: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Campaign ID */
                campaignId: components["parameters"]["CampaignId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Campaign"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimitExceeded"];
        };
    };
    deleteCampaign: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Campaign ID */
                campaignId: components["parameters"]["CampaignId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Campaign archived successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimitExceeded"];
        };
    };
    updateCampaign: {
        parameters: {
            query?: never;
            header?: {
                /** @description Idempotency key for request (valid for 24 hours) */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                /** @description Campaign ID */
                campaignId: components["parameters"]["CampaignId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCampaignRequest"];
            };
        };
        responses: {
            /** @description Campaign updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Campaign"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimitExceeded"];
        };
    };
    listFlows: {
        parameters: {
            query?: {
                /** @description Page number (1-indexed) */
                page?: components["parameters"]["Page"];
                /** @description Number of items per page */
                limit?: components["parameters"]["Limit"];
                /** @description Filter by status */
                status?: components["parameters"]["FilterStatus"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FlowListResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["RateLimitExceeded"];
        };
    };
    createFlow: {
        parameters: {
            query?: never;
            header?: {
                /** @description Idempotency key for request (valid for 24 hours) */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateFlowRequest"];
            };
        };
        responses: {
            /** @description Flow created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Flow"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["RateLimitExceeded"];
        };
    };
    getFlow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Flow ID */
                flowId: components["parameters"]["FlowId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Flow"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimitExceeded"];
        };
    };
    updateFlow: {
        parameters: {
            query?: never;
            header?: {
                /** @description Idempotency key for request (valid for 24 hours) */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                /** @description Flow ID */
                flowId: components["parameters"]["FlowId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateFlowRequest"];
            };
        };
        responses: {
            /** @description Flow updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Flow"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimitExceeded"];
        };
    };
    listCalls: {
        parameters: {
            query?: {
                /** @description Page number (1-indexed) */
                page?: components["parameters"]["Page"];
                /** @description Number of items per page */
                limit?: components["parameters"]["Limit"];
                /** @description Filter by call status */
                status?: components["schemas"]["CallStatus"];
                /** @description Filter by call direction */
                direction?: components["schemas"]["CallDirection"];
                /** @description Filter by campaign ID */
                campaignId?: string;
                /** @description Filter by source phone number */
                fromNumber?: string;
                /** @description Filter by destination phone number */
                toNumber?: string;
                /** @description Filter calls from this date (ISO 8601) */
                startDate?: string;
                /** @description Filter calls until this date (ISO 8601) */
                endDate?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CallListResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["RateLimitExceeded"];
        };
    };
    initiateCall: {
        parameters: {
            query?: never;
            header?: {
                /** @description Idempotency key for request (valid for 24 hours) */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InitiateCallRequest"];
            };
        };
        responses: {
            /** @description Call initiated successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Call"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["RateLimitExceeded"];
        };
    };
    getCall: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Call ID */
                callId: components["parameters"]["CallId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Call"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimitExceeded"];
        };
    };
    listRecordings: {
        parameters: {
            query?: {
                /** @description Page number (1-indexed) */
                page?: components["parameters"]["Page"];
                /** @description Number of items per page */
                limit?: components["parameters"]["Limit"];
                /** @description Filter by call ID */
                callId?: string;
                /** @description Filter by recording status */
                status?: components["schemas"]["RecordingStatus"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordingListResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["RateLimitExceeded"];
        };
    };
    getRecording: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Recording ID */
                recordingId: components["parameters"]["RecordingId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Recording"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimitExceeded"];
        };
    };
    listWebhooks: {
        parameters: {
            query?: {
                /** @description Page number (1-indexed) */
                page?: components["parameters"]["Page"];
                /** @description Number of items per page */
                limit?: components["parameters"]["Limit"];
                /** @description Filter by status */
                status?: components["parameters"]["FilterStatus"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookListResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["RateLimitExceeded"];
        };
    };
    createWebhook: {
        parameters: {
            query?: never;
            header?: {
                /** @description Idempotency key for request (valid for 24 hours) */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWebhookRequest"];
            };
        };
        responses: {
            /** @description Webhook created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Webhook"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["RateLimitExceeded"];
        };
    };
    getWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Webhook ID */
                webhookId: components["parameters"]["WebhookId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Webhook"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimitExceeded"];
        };
    };
    deleteWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Webhook ID */
                webhookId: components["parameters"]["WebhookId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Webhook deleted successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimitExceeded"];
        };
    };
    updateWebhook: {
        parameters: {
            query?: never;
            header?: {
                /** @description Idempotency key for request (valid for 24 hours) */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                /** @description Webhook ID */
                webhookId: components["parameters"]["WebhookId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateWebhookRequest"];
            };
        };
        responses: {
            /** @description Webhook updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Webhook"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimitExceeded"];
        };
    };
    getCallAnalytics: {
        parameters: {
            query: {
                /** @description Start date for analytics (ISO 8601) */
                startDate: string;
                /** @description End date for analytics (ISO 8601) */
                endDate: string;
                /** @description Group results by dimension */
                groupBy?: "day" | "week" | "month" | "campaign" | "status";
                /** @description Filter by campaign ID */
                campaignId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CallAnalyticsResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["RateLimitExceeded"];
        };
    };
    getCampaignPerformance: {
        parameters: {
            query: {
                /** @description Start date for analytics (ISO 8601) */
                startDate: string;
                /** @description End date for analytics (ISO 8601) */
                endDate: string;
            };
            header?: never;
            path: {
                /** @description Campaign ID */
                campaignId: components["parameters"]["CampaignId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignPerformanceResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimitExceeded"];
        };
    };
    listInvoices: {
        parameters: {
            query?: {
                /** @description Page number (1-indexed) */
                page?: components["parameters"]["Page"];
                /** @description Number of items per page */
                limit?: components["parameters"]["Limit"];
                /** @description Filter by invoice status */
                status?: components["schemas"]["InvoiceStatus"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvoiceListResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["RateLimitExceeded"];
        };
    };
    getInvoice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Invoice ID */
                invoiceId: components["parameters"]["InvoiceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Invoice"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimitExceeded"];
        };
    };
    getAccountBalance: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BalanceResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["RateLimitExceeded"];
        };
    };
    adminListTenants: {
        parameters: {
            query?: {
                /** @description Page number (1-indexed) */
                page?: components["parameters"]["Page"];
                /** @description Number of items per page */
                limit?: components["parameters"]["Limit"];
                /** @description Filter by status */
                status?: components["parameters"]["FilterStatus"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantListResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["RateLimitExceeded"];
        };
    };
    adminCreateTenant: {
        parameters: {
            query?: never;
            header?: {
                /** @description Idempotency key for request (valid for 24 hours) */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminCreateTenantRequest"];
            };
        };
        responses: {
            /** @description Tenant created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tenant"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["RateLimitExceeded"];
        };
    };
    adminGetTenant: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Tenant ID */
                tenantId: components["parameters"]["TenantId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tenant"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimitExceeded"];
        };
    };
    adminUpdateTenant: {
        parameters: {
            query?: never;
            header?: {
                /** @description Idempotency key for request (valid for 24 hours) */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                /** @description Tenant ID */
                tenantId: components["parameters"]["TenantId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminUpdateTenantRequest"];
            };
        };
        responses: {
            /** @description Tenant updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tenant"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimitExceeded"];
        };
    };
    adminProvisionNumber: {
        parameters: {
            query?: never;
            header?: {
                /** @description Idempotency key for request (valid for 24 hours) */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminProvisionNumberRequest"];
            };
        };
        responses: {
            /** @description Number provisioned successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhoneNumber"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["RateLimitExceeded"];
        };
    };
    adminListCarriers: {
        parameters: {
            query?: {
                /** @description Page number (1-indexed) */
                page?: components["parameters"]["Page"];
                /** @description Number of items per page */
                limit?: components["parameters"]["Limit"];
                /** @description Filter by status */
                status?: components["parameters"]["FilterStatus"];
                /** @description Filter by tenant ID */
                tenantId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CarrierListResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["RateLimitExceeded"];
        };
    };
    adminCreateCarrier: {
        parameters: {
            query?: never;
            header?: {
                /** @description Idempotency key for request (valid for 24 hours) */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminCreateCarrierRequest"];
            };
        };
        responses: {
            /** @description Carrier created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Carrier"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["RateLimitExceeded"];
        };
    };
    adminGetCarrier: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Carrier ID */
                carrierId: components["parameters"]["CarrierId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Carrier"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimitExceeded"];
        };
    };
    adminUpdateCarrier: {
        parameters: {
            query?: never;
            header?: {
                /** @description Idempotency key for request (valid for 24 hours) */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                /** @description Carrier ID */
                carrierId: components["parameters"]["CarrierId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminUpdateCarrierRequest"];
            };
        };
        responses: {
            /** @description Carrier updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Carrier"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimitExceeded"];
        };
    };
    adminListTrunks: {
        parameters: {
            query?: {
                /** @description Page number (1-indexed) */
                page?: components["parameters"]["Page"];
                /** @description Number of items per page */
                limit?: components["parameters"]["Limit"];
                /** @description Filter by status */
                status?: components["parameters"]["FilterStatus"];
                /** @description Filter by tenant ID */
                tenantId?: string;
                /** @description Filter by carrier ID */
                carrierId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrunkListResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["RateLimitExceeded"];
        };
    };
    adminCreateTrunk: {
        parameters: {
            query?: never;
            header?: {
                /** @description Idempotency key for request (valid for 24 hours) */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminCreateTrunkRequest"];
            };
        };
        responses: {
            /** @description Trunk created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Trunk"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["RateLimitExceeded"];
        };
    };
    adminGetTrunk: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Trunk ID */
                trunkId: components["parameters"]["TrunkId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Trunk"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimitExceeded"];
        };
    };
    adminUpdateTrunk: {
        parameters: {
            query?: never;
            header?: {
                /** @description Idempotency key for request (valid for 24 hours) */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                /** @description Trunk ID */
                trunkId: components["parameters"]["TrunkId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminUpdateTrunkRequest"];
            };
        };
        responses: {
            /** @description Trunk updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Trunk"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimitExceeded"];
        };
    };
    adminListRateCards: {
        parameters: {
            query?: {
                /** @description Page number (1-indexed) */
                page?: components["parameters"]["Page"];
                /** @description Number of items per page */
                limit?: components["parameters"]["Limit"];
                /** @description Filter by status */
                status?: components["parameters"]["FilterStatus"];
                /** @description Filter by billing account ID */
                billingAccountId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RateCardListResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["RateLimitExceeded"];
        };
    };
    adminCreateRateCard: {
        parameters: {
            query?: never;
            header?: {
                /** @description Idempotency key for request (valid for 24 hours) */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminCreateRateCardRequest"];
            };
        };
        responses: {
            /** @description Rate card created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RateCard"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["RateLimitExceeded"];
        };
    };
    adminGetRateCard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Rate card ID */
                rateCardId: components["parameters"]["RateCardId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RateCard"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimitExceeded"];
        };
    };
    adminUpdateRateCard: {
        parameters: {
            query?: never;
            header?: {
                /** @description Idempotency key for request (valid for 24 hours) */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                /** @description Rate card ID */
                rateCardId: components["parameters"]["RateCardId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminUpdateRateCardRequest"];
            };
        };
        responses: {
            /** @description Rate card updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RateCard"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimitExceeded"];
        };
    };
}