ALTER TABLE users ADD COLUMN IF NOT EXISTS "googleId" VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS "authMethod" VARCHAR(20) NOT NULL DEFAULT 'EMAIL';
ALTER TABLE users ALTER COLUMN "tenantId" DROP NOT NULL;
ALTER TABLE users ALTER COLUMN "passwordHash" DROP NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS users_googleid_unique ON users("googleId");
CREATE UNIQUE INDEX IF NOT EXISTS users_email_unique ON users(email);
