/**
 * Applications: the agency's own record of the business it wrote.
 *
 * ── What this surface is for ─────────────────────────────────────────────────
 *
 * `POST /api/v1/applications` is the carrier-agnostic way an application enters
 * the closing percentage. Everything it writes goes through
 * `services/applications/agent-entry.ts`, which explains why it exists: until
 * it, only the American Amicable RPA could set `submittedAt`, so business
 * written with the other ten carriers on the quote panel was never counted, and
 * an uncounted application is a lower closing percentage and a HIGHER price.
 *
 * The reads below are the screen an agency owner reconciles against carrier
 * statements, and the screen an agent checks their own day on.
 *
 * ── Nothing here takes a tenant from the wire ────────────────────────────────
 *
 * Every route resolves the acting tenant through `resolveTenant` /
 * `getActingUserId`, which read the authenticated principal and nothing else.
 * No body, query parameter or header names an agency. The tenant is the
 * boundary between two agencies' numerators, and their prices.
 *
 * ── An agent sees their own rows, and the server decides that ────────────────
 *
 * An AGENT's reads are narrowed to `createdById = their own userId`, and the
 * narrowing OVERWRITES whatever `agentId` they sent rather than validating it.
 * A filter the client can set is a filter the client can unset.
 *
 * ── Voiding is platform staff only ───────────────────────────────────────────
 *
 * An agency cannot void its own applications. The numerator is what its price
 * is measured from, so an agency that could remove rows from it could set its
 * own rate. Voiding also writes NOTHING to `application_credit_ledger`: that
 * table refuses UPDATE and DELETE by trigger and has no reversal entry type by
 * design, and a credit already consumed stays consumed.
 */

import { Prisma } from '@prisma/client';
import type { FastifyInstance } from 'fastify';
import { z } from 'zod';

import { requirePlatformAdmin } from '../lib/platform-context.js';
import { getPrismaClient } from '../lib/prisma.js';
import { getActingUserId, resolveTenant } from '../lib/tenant-context.js';
import { authenticate } from '../middleware/auth.js';
import { recordAgentApplication } from '../services/applications/agent-entry.js';
import type { PaymentMode } from '../services/applications/agent-entry.js';
import { auditLog } from '../services/audit.js';
import { toMaskedApplicationResponse } from '../services/carrier-rpa/application-store.js';
import { calendarDayBounds } from '../services/rating/calendar-day.js';

const DAY_PATTERN = /^\d{4}-\d{2}-\d{2}$/;

/** The roles that may log business for the agency. */
const CAN_LOG_ROLES = ['AGENT', 'ADMIN', 'OWNER'];
/** The roles that see the whole agency rather than only their own rows. */
const AGENCY_PRINCIPAL_ROLES = ['ADMIN', 'OWNER'];

interface RoutePrincipal {
  userId?: string;
  roles?: string[];
}

function rolesOf(request: { user?: RoutePrincipal }): string[] {
  return request.user?.roles ?? [];
}

const CreateApplicationSchema = z.object({
  /*
   * Generated by the agent's client when the form MOUNTS and reused on every
   * retry, so a submit that timed out after the row landed and the Retry that
   * follows it are one application. Required rather than optional: an
   * idempotency key the client may omit is one the client will omit on exactly
   * the request that needed it.
   */
  clientRequestId: z.string().uuid(),
  callId: z.string().optional(),
  insuranceLeadId: z.string().optional(),

  carrier: z.string().min(1).max(80),
  product: z.string().optional(),
  planType: z.enum(['LEVEL', 'GRADED', 'ROP', 'GUARANTEED_ISSUE']).optional(),
  faceAmount: z.number().int().min(1000).max(500000),
  modalPremium: z.number().positive().max(5000),
  paymentMode: z.enum(['MONTHLY', 'QUARTERLY', 'SEMI_ANNUAL', 'ANNUAL']).default('MONTHLY'),
  carrierApplicationNumber: z.string().optional(),

  firstName: z.string().min(1),
  lastName: z.string().min(1),
  dob: z
    .string()
    .regex(/^\d{2}\/\d{2}\/\d{4}$/, 'dob must be MM/DD/YYYY')
    .optional(),
  state: z.string().optional(),
  phone: z.string().optional(),
  notes: z.string().optional(),
});

const VoidSchema = z.object({
  reason: z.string().min(5).max(500),
});

/** A number off a Prisma Decimal, or null. */
function toNumber(value: Prisma.Decimal | number | null | undefined): number | null {
  if (value === null || value === undefined) return null;
  return typeof value === 'number' ? value : Number(value);
}

/**
 * The applicant, as much of them as this surface shows.
 *
 * First name and last INITIAL. Enough for an agency to match a row against a
 * carrier statement or an agent to recognise their own call, and not a
 * downloadable list of the names of everyone an agency insured. The CSV export
 * on the page reads this same field.
 */
function applicantLabel(firstName: string, lastName: string): string {
  const initial = lastName.trim().charAt(0);
  return initial ? `${firstName} ${initial}.` : firstName;
}

/** The instant range for a `from`/`to` pair of calendar day keys. */
function rangeFor(from?: string, to?: string): { gte?: Date; lt?: Date } {
  const range: { gte?: Date; lt?: Date } = {};
  if (from) range.gte = calendarDayBounds(from).start;
  if (to) range.lt = calendarDayBounds(to).endExclusive;
  return range;
}

// eslint-disable-next-line @typescript-eslint/require-await -- plugin signature
export async function registerApplicationRoutes(fastify: FastifyInstance): Promise<void> {
  const prisma = getPrismaClient();

  /**
   * POST /api/v1/applications
   *
   * An agent logs business they wrote themselves, on any carrier.
   */
  fastify.post('/api/v1/applications', { preHandler: [authenticate] }, async (request, reply) => {
    const tenantId = resolveTenant(request, reply);
    if (!tenantId) return;

    const userId = getActingUserId(request);
    if (!userId) {
      /*
       * `createdById` is what `getAgentBreakdown` attributes production by, and
       * an application with none is a row nobody wrote. An API key has no
       * person behind it, so it cannot log business for one.
       */
      return reply.code(403).send({
        error: {
          code: 'FORBIDDEN',
          message: 'An application is logged by a person; this credential is not one.',
        },
      });
    }

    const roles = rolesOf(request as { user?: RoutePrincipal });
    if (!roles.some(role => CAN_LOG_ROLES.includes(role))) {
      return reply.code(403).send({
        error: {
          code: 'FORBIDDEN',
          message: 'Only an agent, administrator or owner can log an application.',
        },
      });
    }

    const parsed = CreateApplicationSchema.safeParse(request.body);
    if (!parsed.success) {
      return reply.code(400).send({
        error: {
          code: 'VALIDATION_ERROR',
          message: parsed.error.issues.map(i => `${i.path.join('.')}: ${i.message}`).join('; '),
        },
      });
    }
    const body = parsed.data;

    /*
     * A call id is verified against this tenant, and NOT required.
     *
     * Verified, because a call id is the one identifier on this body that
     * points at another row, and accepting one from another agency would
     * attribute an application to a call its owner cannot see.
     *
     * Not required, because an application written on a callback after the
     * softphone session ended has no call to attach, and refusing it would push
     * the agent back to the state this whole feature exists to remove: business
     * written and never counted.
     */
    if (body.callId) {
      const call = await prisma.call.findFirst({
        where: { id: body.callId, tenantId },
        select: { id: true },
      });
      if (!call) {
        return reply.code(404).send({
          error: { code: 'CALL_NOT_FOUND', message: 'No such call for this agency.' },
        });
      }
    }

    const application = await recordAgentApplication({
      tenantId,
      createdById: userId,
      clientRequestId: body.clientRequestId,
      callId: body.callId ?? null,
      insuranceLeadId: body.insuranceLeadId ?? null,
      carrier: body.carrier,
      product: body.product ?? null,
      planType: body.planType ?? null,
      faceAmount: body.faceAmount,
      modalPremium: body.modalPremium,
      paymentMode: body.paymentMode as PaymentMode,
      carrierApplicationNumber: body.carrierApplicationNumber ?? null,
      firstName: body.firstName,
      lastName: body.lastName,
      dob: body.dob ?? null,
      state: body.state ?? null,
      phone: body.phone ?? null,
    });

    return reply.code(201).send({ data: toMaskedApplicationResponse(application) });
  });

  /**
   * GET /api/v1/applications
   *
   * The reconciliation table. An ADMIN or OWNER sees the whole agency; an AGENT
   * sees only the rows they wrote.
   */
  fastify.get<{
    Querystring: {
      from?: string;
      to?: string;
      agentId?: string;
      carrier?: string;
      limit?: string;
      cursor?: string;
    };
  }>('/api/v1/applications', { preHandler: [authenticate] }, async (request, reply) => {
    const tenantId = resolveTenant(request, reply);
    if (!tenantId) return;

    const { from, to, carrier, cursor } = request.query;
    for (const [name, value] of [
      ['from', from],
      ['to', to],
    ] as const) {
      if (value !== undefined && !DAY_PATTERN.test(value)) {
        return reply.code(400).send({
          error: { code: 'VALIDATION_ERROR', message: `${name} must be YYYY-MM-DD` },
        });
      }
    }

    const limit = Math.min(Math.max(Number(request.query.limit ?? 100) || 100, 1), 500);

    const roles = rolesOf(request as { user?: RoutePrincipal });
    const isPrincipal = roles.some(role => AGENCY_PRINCIPAL_ROLES.includes(role));
    /*
     * The narrowing is an OVERWRITE, not a check. An agent's `agentId` is their
     * own user id whatever they sent, so there is no value they can put on the
     * query string that widens what comes back. The impossible id is the
     * fallback for a principal with no user id at all -- an API key -- which
     * must come back with nothing rather than with the agency.
     */
    const agentId = isPrincipal ? request.query.agentId : (getActingUserId(request) ?? ' ');

    const rows = await prisma.insuranceCarrierApplication.findMany({
      where: {
        tenantId,
        // Only applications that reached submitted state. A PENDING RPA row is
        // not business the agency wrote.
        submittedAt: { not: null, ...rangeFor(from, to) },
        ...(agentId ? { createdById: agentId } : {}),
        ...(carrier ? { carrier } : {}),
      },
      orderBy: [{ submittedAt: 'desc' }, { id: 'desc' }],
      take: limit,
      ...(cursor ? { cursor: { id: cursor }, skip: 1 } : {}),
      select: {
        id: true,
        submittedAt: true,
        source: true,
        carrier: true,
        product: true,
        planType: true,
        faceAmount: true,
        modalPremium: true,
        paymentMode: true,
        annualizedPremium: true,
        firstName: true,
        lastName: true,
        state: true,
        carrierApplicationNumber: true,
        createdById: true,
        callId: true,
        voidedAt: true,
        voidReason: true,
      },
    });

    const agentIds = [...new Set(rows.map(row => row.createdById).filter(Boolean))] as string[];
    const users = agentIds.length
      ? await prisma.user.findMany({
          where: { id: { in: agentIds }, tenantId },
          select: { id: true, email: true, firstName: true, lastName: true },
        })
      : [];
    const nameById = new Map(
      users.map(u => [u.id, [u.firstName, u.lastName].filter(Boolean).join(' ') || u.email || u.id])
    );

    return reply.send({
      data: {
        applications: rows.map(row => ({
          id: row.id,
          submittedAt: row.submittedAt?.toISOString() ?? null,
          source: row.source,
          carrier: row.carrier,
          product: row.product,
          planType: row.planType,
          faceAmount: row.faceAmount,
          modalPremium: toNumber(row.modalPremium),
          paymentMode: row.paymentMode,
          annualizedPremium: toNumber(row.annualizedPremium),
          applicant: applicantLabel(row.firstName, row.lastName),
          state: row.state,
          carrierApplicationNumber: row.carrierApplicationNumber,
          agentId: row.createdById,
          agentName: row.createdById ? (nameById.get(row.createdById) ?? null) : null,
          callId: row.callId,
          voidedAt: row.voidedAt?.toISOString() ?? null,
          voidReason: row.voidReason,
        })),
        // Null when the page was not full: there is nothing after it.
        nextCursor: rows.length === limit ? rows[rows.length - 1].id : null,
      },
    });
  });

  /**
   * GET /api/v1/applications/summary
   *
   * The strip across the top of the applications page: how many, how much
   * annualised premium, and the same two broken down by carrier and by agent.
   *
   * Voided rows are excluded here exactly as they are from the closing
   * percentage. The table below still shows them, struck through, because an
   * agency reconciling a statement needs to see that a row was voided rather
   * than find it missing; a total that included them would reconcile with
   * nothing.
   */
  fastify.get<{ Querystring: { from?: string; to?: string } }>(
    '/api/v1/applications/summary',
    { preHandler: [authenticate] },
    async (request, reply) => {
      const tenantId = resolveTenant(request, reply);
      if (!tenantId) return;

      const { from, to } = request.query;
      for (const [name, value] of [
        ['from', from],
        ['to', to],
      ] as const) {
        if (value !== undefined && !DAY_PATTERN.test(value)) {
          return reply.code(400).send({
            error: { code: 'VALIDATION_ERROR', message: `${name} must be YYYY-MM-DD` },
          });
        }
      }

      const roles = rolesOf(request as { user?: RoutePrincipal });
      const isPrincipal = roles.some(role => AGENCY_PRINCIPAL_ROLES.includes(role));
      const agentId = isPrincipal ? undefined : (getActingUserId(request) ?? ' ');

      const where: Prisma.InsuranceCarrierApplicationWhereInput = {
        tenantId,
        submittedAt: { not: null, ...rangeFor(from, to) },
        voidedAt: null,
        ...(agentId ? { createdById: agentId } : {}),
      };

      const [byCarrier, byAgent] = await Promise.all([
        prisma.insuranceCarrierApplication.groupBy({
          by: ['carrier'],
          where,
          _count: { _all: true },
          _sum: { annualizedPremium: true },
        }),
        prisma.insuranceCarrierApplication.groupBy({
          by: ['createdById'],
          where,
          _count: { _all: true },
          _sum: { annualizedPremium: true },
        }),
      ]);

      const count = byCarrier.reduce((total, row) => total + row._count._all, 0);
      const totalAnnualizedPremium = byCarrier.reduce(
        (total, row) => total + (toNumber(row._sum.annualizedPremium) ?? 0),
        0
      );

      const agentIds = byAgent.map(row => row.createdById).filter(Boolean) as string[];
      const users = agentIds.length
        ? await prisma.user.findMany({
            where: { id: { in: agentIds }, tenantId },
            select: { id: true, email: true, firstName: true, lastName: true },
          })
        : [];
      const nameById = new Map(
        users.map(u => [
          u.id,
          [u.firstName, u.lastName].filter(Boolean).join(' ') || u.email || u.id,
        ])
      );

      return reply.send({
        data: {
          count,
          totalAnnualizedPremium: Number(totalAnnualizedPremium.toFixed(2)),
          /*
           * Null rather than 0 for an empty range. An average of nothing is not
           * zero dollars of premium, and rendering it as a price would say the
           * agency wrote business worth nothing.
           */
          averageAnnualizedPremium:
            count > 0 ? Number((totalAnnualizedPremium / count).toFixed(2)) : null,
          byCarrier: byCarrier
            .map(row => ({
              carrier: row.carrier,
              count: row._count._all,
              annualizedPremium: Number((toNumber(row._sum.annualizedPremium) ?? 0).toFixed(2)),
            }))
            .sort((a, b) => b.count - a.count),
          byAgent: byAgent
            .map(row => ({
              agentId: row.createdById,
              agentName: row.createdById
                ? (nameById.get(row.createdById) ?? row.createdById)
                : 'Unattributed',
              count: row._count._all,
              annualizedPremium: Number((toNumber(row._sum.annualizedPremium) ?? 0).toFixed(2)),
            }))
            .sort((a, b) => b.count - a.count),
        },
      });
    }
  );

  /**
   * POST /api/v1/applications/:id/void
   *
   * Platform staff remove an application from the measurement.
   *
   * Writes no ledger row and touches `application_credit_ledger` not at all.
   * That table refuses UPDATE and DELETE by trigger and there is no reversal
   * entry type by design: voiding corrects what the agency is measured on, it
   * does not refund a credit that was already consumed.
   */
  fastify.post<{ Params: { id: string } }>(
    '/api/v1/applications/:id/void',
    { preHandler: [authenticate, requirePlatformAdmin] },
    async (request, reply) => {
      const parsed = VoidSchema.safeParse(request.body);
      if (!parsed.success) {
        return reply.code(400).send({
          error: {
            code: 'VALIDATION_ERROR',
            message: parsed.error.issues.map(i => `${i.path.join('.')}: ${i.message}`).join('; '),
          },
        });
      }

      const application = await prisma.insuranceCarrierApplication.findUnique({
        where: { id: request.params.id },
        select: { id: true, tenantId: true, voidedAt: true, submittedAt: true, carrier: true },
      });

      if (!application) {
        return reply.code(404).send({
          error: { code: 'NOT_FOUND', message: 'No such application.' },
        });
      }

      if (application.voidedAt) {
        return reply.code(409).send({
          error: {
            code: 'ALREADY_VOIDED',
            message: `This application was voided on ${application.voidedAt.toISOString()}.`,
          },
        });
      }

      const operatorId = getActingUserId(request);

      const updated = await prisma.insuranceCarrierApplication.update({
        where: { id: application.id },
        data: {
          voidedAt: new Date(),
          voidedById: operatorId,
          voidReason: parsed.data.reason,
        },
        select: { id: true, voidedAt: true, voidedById: true, voidReason: true },
      });

      await auditLog({
        tenantId: application.tenantId,
        userId: operatorId ?? undefined,
        action: 'application.voided',
        entityType: 'InsuranceCarrierApplication',
        entityId: application.id,
        changes: {
          before: { voidedAt: null },
          after: {
            voidedAt: updated.voidedAt?.toISOString() ?? null,
            voidReason: updated.voidReason,
          },
          // Recorded on the audit row so the effect on the agency's numerator
          // is readable without going back to the application.
          submittedAt: application.submittedAt?.toISOString() ?? null,
          carrier: application.carrier,
        },
        resource: request.url,
        method: request.method,
        success: true,
      });

      return reply.send({
        data: {
          id: updated.id,
          voidedAt: updated.voidedAt?.toISOString() ?? null,
          voidedById: updated.voidedById,
          voidReason: updated.voidReason,
        },
      });
    }
  );
}
