/**
 * The FreeSWITCH user directory, served from the database.
 *
 * ── What this is ─────────────────────────────────────────────────────────────
 *
 * `mod_xml_curl` lets FreeSWITCH ask an HTTP endpoint for a section of its
 * configuration instead of reading it from disk. This endpoint answers the
 * `directory` section: FreeSWITCH presents a SIP username and asks who it is
 * and what its password is, and this replies with the XML for that one user.
 *
 * ── Why the directory could not stay on disk ─────────────────────────────────
 *
 * It was twenty files, `apps/freeswitch/conf/directory/default/1000.xml`
 * through `1019.xml`, each one `<param name="password" value="$${default_password}"/>`.
 * Static files cannot express a per-agent secret and cannot grow past the files
 * somebody wrote, so the product inherited both properties: a twenty-agent
 * ceiling, and one password that authenticated every extension on the platform
 * for every agent who held it. The full account is on the `AgentSipCredential`
 * model.
 *
 * ── Not found is an answer, and it matters ───────────────────────────────────
 *
 * When this endpoint returns the `result`/`not found` document, FreeSWITCH
 * falls through to the next binding for the section -- which is the static XML
 * still on disk. That is deliberate and it is the migration path: `vapi.xml`,
 * `demo-agent.xml` and any 1000..1019 file still resolve exactly as before,
 * while every agent provisioned through `AgentSipCredential` is answered from
 * here. Nothing has to be cut over in one step.
 *
 * It also means a wrong answer is worse than no answer. Every path that cannot
 * establish who the caller is returns not-found rather than a guess.
 *
 * ── The password crosses the wire in the clear ───────────────────────────────
 *
 * It has to: FreeSWITCH needs the shared secret to compute the digest response
 * it compares against the one the softphone sent. That is what the internal key
 * guard and a private network are for, and it is the same property the static
 * files had -- `$${default_password}` was a cleartext password in a file on the
 * same host. What changes is the blast radius: one directory lookup now reveals
 * one agent's secret rather than the whole platform's.
 *
 * `lib/internal-auth.ts` records why the guard is a shared secret and why it is
 * accepted on the query string as well as the header.
 */

import type { FastifyInstance, FastifyReply, FastifyRequest } from 'fastify';

import { requireInternalKey } from '../lib/internal-auth.js';
import { getPrismaClient } from '../lib/prisma.js';
import { lookupDirectoryPrincipal } from '../services/telephony/agent-sip-credential.js';

/**
 * The document that means "I have nothing for this, ask the next binding".
 *
 * FreeSWITCH matches on `<section name="result">` with a `not found` status, so
 * the string is exact. Anything else -- an error page, an empty body, a 500 --
 * is a parse failure to mod_xml_curl, which it logs and treats as a hard
 * failure rather than as a fall-through.
 */
const NOT_FOUND_DOCUMENT = `<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<document type="freeswitch/xml">
  <section name="result">
    <result status="not found"/>
  </section>
</document>`;

/**
 * XML text escaping for the four characters that would otherwise change the
 * shape of the document.
 *
 * The password is generated by `agent-sip-credential.ts` as base64url, whose
 * alphabet contains none of these -- so today this escapes nothing. It is here
 * because the day somebody changes the generator is the day an unescaped `&`
 * in a password produces a directory document FreeSWITCH refuses to parse, and
 * every agent whose extension sorts after it stops registering.
 */
function xmlEscape(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

/**
 * One agent's directory entry.
 *
 * The params and variables mirror `apps/freeswitch/conf/directory/default/1000.xml`
 * so an agent served from here behaves identically to one served from disk --
 * same Verto method allowlist, same context, same toll permissions. Two
 * differences, both intentional:
 *
 *   * `password` is this agent's own secret rather than `$${default_password}`;
 *   * `hopwhistle_tenant_id` and `hopwhistle_user_id` are exported onto every
 *     channel the agent originates, so a call carries the agency that owns it
 *     from the first INVITE rather than being matched back to one later.
 */
function directoryDocument(params: {
  domain: string;
  extension: string;
  password: string;
  tenantId: string;
  userId: string;
}): string {
  const { domain, extension, password, tenantId, userId } = params;

  return `<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<document type="freeswitch/xml">
  <section name="directory">
    <domain name="${xmlEscape(domain)}">
      <params>
        <param name="dial-string" value="{^^:sip_invite_domain=\${dialed_domain}:presence_id=\${dialed_user}@\${dialed_domain}}\${sofia_contact(*/\${dialed_user}@\${dialed_domain})},\${verto_contact(\${dialed_user}@\${dialed_domain})}"/>
      </params>
      <groups>
        <group name="default">
          <users>
            <user id="${xmlEscape(extension)}">
              <params>
                <param name="password" value="${xmlEscape(password)}"/>
                <param name="vm-password" value="${xmlEscape(extension)}"/>
                <param name="jsonrpc-allowed-methods" value="verto.invite,verto.answer,verto.attach,verto.info,verto.display,verto.bye,verto.modify,verto.media,verto.ping"/>
              </params>
              <variables>
                <variable name="toll_allow" value="domestic,international,local"/>
                <variable name="accountcode" value="${xmlEscape(extension)}"/>
                <variable name="user_context" value="default"/>
                <variable name="verto_context" value="default"/>
                <variable name="verto_dialplan" value="XML"/>
                <variable name="effective_caller_id_number" value="${xmlEscape(extension)}"/>
                <variable name="outbound_caller_id_name" value="Hopwhistle"/>
                <variable name="hopwhistle_tenant_id" value="${xmlEscape(tenantId)}"/>
                <variable name="hopwhistle_user_id" value="${xmlEscape(userId)}"/>
              </variables>
            </user>
          </users>
        </group>
      </groups>
    </domain>
  </section>
</document>`;
}

/**
 * The fields mod_xml_curl posts, as `application/x-www-form-urlencoded`.
 *
 * Only `section`, `key_value` and `user` are read. `key_value` carries the SIP
 * username on an authentication lookup; `user` carries it on a `user_call`
 * lookup. Both are consulted because FreeSWITCH sends the two lookups for
 * different reasons and does not populate the same field in each.
 */
interface DirectoryLookupBody {
  section?: string;
  tag_name?: string;
  key_name?: string;
  key_value?: string;
  user?: string;
  domain?: string;
  action?: string;
}

export async function registerFreeswitchDirectoryRoutes(fastify: FastifyInstance): Promise<void> {
  /*
   * mod_xml_curl posts `application/x-www-form-urlencoded`, which Fastify does
   * not parse without this. Registered on THIS plugin's instance rather than on
   * the root: Fastify encapsulates content-type parsers per scope, and
   * `routes/signalwire-webhooks.ts` already registers the same plugin in its
   * own scope. Two registrations on one instance is a startup error; two
   * registrations in two scopes is how the framework is meant to be used.
   *
   * Without it `request.body` is undefined, every lookup reads an empty
   * extension, and every agent on the box silently fails to register.
   */
  await fastify.register(import('@fastify/formbody'));

  const prisma = getPrismaClient();

  /**
   * POST /api/v1/freeswitch/directory
   *
   * Answers one directory lookup. Always 200 with an XML body: a non-200 is not
   * a fall-through to mod_xml_curl, it is a failed fetch, and a failed fetch on
   * the directory section is every agent on the box unable to register.
   */
  fastify.post(
    '/api/v1/freeswitch/directory',
    { preHandler: [requireInternalKey] },
    async (request: FastifyRequest, reply: FastifyReply) => {
      const body = (request.body ?? {}) as DirectoryLookupBody;

      void reply.type('text/xml; charset=utf-8');

      // FreeSWITCH asks one endpoint for whichever sections it is bound to.
      // Answering a `dialplan` or `configuration` lookup with a directory
      // document would be a parse error, so anything that is not the directory
      // falls straight through to the static XML.
      if (body.section !== 'directory') {
        return reply.send(NOT_FOUND_DOCUMENT);
      }

      const extension = (body.key_value ?? body.user ?? '').trim();
      if (!extension) {
        return reply.send(NOT_FOUND_DOCUMENT);
      }

      /*
       * `domain` is echoed back as FreeSWITCH sent it rather than read from
       * configuration here. The directory document has to name the domain the
       * lookup was FOR -- reply with a different one and FreeSWITCH finds no
       * user in it, which presents as a registration that fails with the
       * correct password.
       */
      const domain = (body.domain ?? '').trim();
      if (!domain) {
        return reply.send(NOT_FOUND_DOCUMENT);
      }

      try {
        const principal = await lookupDirectoryPrincipal(extension, { prisma });

        if (!principal) {
          // Expected constantly: every static-file extension, every revoked
          // credential, every probe from the internet that got this far. Logged
          // at debug so it does not drown the telephony logs.
          request.log.debug(
            { event: 'freeswitch_directory_miss', extension, domain },
            'No database credential for this extension; falling through to static XML'
          );
          return reply.send(NOT_FOUND_DOCUMENT);
        }

        request.log.debug(
          {
            event: 'freeswitch_directory_hit',
            extension,
            domain,
            tenantId: principal.tenantId,
          },
          'Served a directory entry'
        );

        return reply.send(
          directoryDocument({
            domain,
            extension: principal.extension,
            password: principal.password,
            tenantId: principal.tenantId,
            userId: principal.userId,
          })
        );
      } catch (error) {
        /*
         * A database or decryption failure is not a missing user, but it has to
         * be answered as one: the alternative is a non-200, which mod_xml_curl
         * treats as a failed fetch rather than a fall-through. Logged at error
         * so the cause is findable -- the symptom on the floor is one agent who
         * cannot register.
         */
        request.log.error(
          { event: 'freeswitch_directory_error', extension, domain, err: error },
          'Directory lookup failed; answering not-found so the static XML is consulted'
        );
        return reply.send(NOT_FOUND_DOCUMENT);
      }
    }
  );
}
